# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.15 on 2026-10-07 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def clients_from_labels(apps, schema_editor):
    """Cards already tagged with a client's label get that client (cards with labels of two clients are skipped)."""
    ClientLabel = apps.get_model("db", "ClientLabel")
    IssueLabel = apps.get_model("db", "IssueLabel")
    IssueClient = apps.get_model("db", "IssueClient")
    client_of_label = dict(ClientLabel.objects.filter(deleted_at__isnull=True).values_list("label_id", "client_id"))
    if not client_of_label:
        return
    clients_by_issue = {}
    rows = IssueLabel.objects.filter(deleted_at__isnull=True, label_id__in=list(client_of_label)).values_list(
        "issue_id", "label_id", "project_id", "workspace_id"
    )
    for issue_id, label_id, project_id, workspace_id in rows:
        entry = clients_by_issue.setdefault(issue_id, {"clients": set(), "project": project_id, "ws": workspace_id})
        entry["clients"].add(client_of_label[label_id])
    IssueClient.objects.bulk_create(
        [
            IssueClient(
                issue_id=issue_id, client_id=next(iter(e["clients"])), project_id=e["project"], workspace_id=e["ws"]
            )
            for issue_id, e in clients_by_issue.items()
            if len(e["clients"]) == 1
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0133_conjo_client_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueClient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="issue_links", to="db.client"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="conjo_clients", to="db.issue"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "IssueClient",
                "verbose_name_plural": "IssueClients",
                "db_table": "conjo_issue_clients",
            },
        ),
        migrations.AddConstraint(
            model_name="issueclient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue",),
                name="conjo_issue_client_unique_issue",
            ),
        ),
        migrations.RunPython(clients_from_labels, migrations.RunPython.noop),
    ]
